# hasura/config.yaml
HASURA_GRAPHQL_JWT_SECRET: {
    "type": "HS256",
    "key": "73r&1x_szx$sj!kn3&x_am)xv$3f5@59u04k!c(95%=p0421jt",  # Must match Django's SIGNING_KEY
    "claims_namespace": "https://hasura.io/jwt/claims",
    "claims_format": "json"
}

HASURA_GRAPHQL_ADMIN_SECRET: "your-admin-secret"
HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"